Fixes #5924 - Javadoc build triggers maven error
Fixed javadoc generation error.
Apparently, this is caused by a doxia dependency of asciidoctor-maven-plugin
that transitively pulls in Apache HttpClient, but at an older version
that causes this error:

Exception in thread “main” java.lang.NoSuchMethodError: ‘org.apache.http.HttpHost org.apache.http.client.utils.URIUtils.extractHost(java.net.URI)’

Adding Apache HttpClient as an explicit dependency of the asciidoctor-maven-plugin
works around the issue.

Co-authored-by: olivier lamy <oliver.lamy@gmail.com>
Signed-off-by: Simone Bordet <simone.bordet@gmail.com>